#!/bin/bash

echo "🚀 Portfolio Upload to GitHub"
echo "=============================="
echo ""
echo "All files are ready to upload!"
echo "Repository: https://github.com/Gokulakrishnxn/Gokulakrishnan.dev.git"
echo ""
echo "📁 Files to upload:"
echo "✅ 56 files committed and ready"
echo "✅ Portfolio with all features"
echo "✅ Company logos and external links"
echo "✅ Smooth animations and responsive design"
echo ""
echo "🔧 Upload Methods:"
echo ""
echo "Method 1 - GitHub Web Interface (Recommended):"
echo "1. Go to: https://github.com/Gokulakrishnxn/Gokulakrishnan.dev"
echo "2. Click 'uploading an existing file'"
echo "3. Drag and drop ALL files from this folder"
echo "4. Commit with message: 'Initial portfolio commit'"
echo ""
echo "Method 2 - Fix Git Authentication:"
echo "1. Configure Git: git config --global user.name 'Gokulakrishnxn'"
echo "2. Configure Git: git config --global user.email 'your-email@example.com'"
echo "3. Create Personal Access Token at: https://github.com/settings/tokens"
echo "4. Run: git push -u origin main"
echo ""
echo "Method 3 - GitHub Desktop:"
echo "1. Download: https://desktop.github.com"
echo "2. Clone repository and copy files"
echo "3. Commit and push through GitHub Desktop"
echo ""
echo "🎉 Your portfolio is ready with all features!"
